### ISSUE TITLE
Possible to use upstream scrcpy after virtual-display feature was added officially ?

### ISSUE THREAD

**Issue by sidevesh** [rsanjuan87/FUP#1]
Scrcpy recently merged in virtual display feature at https://github.com/Genymobile/scrcpy/commit/98ed5eb643553b6886babfd083931bef4fb4a5b8

Would it be possible to now shift to using upstream scrcpy instead of the fork or is there anything missing or differently implemented in that commit which would require the fork still ?

Great work on the app btw and really looking forward to it releasing :)

**Comment by rsanjuan87** [comment]
Yes, now scrcpy is shipping with this new feature
This fork was from a unstable and unofficial version of scrcpy with a new virtual display feature
I will update, Thanks
you may contribute with PR .....
